### ISSUE TITLE
Why not install-less approach?

### ISSUE THREAD

**Issue by vitaly-t** [oguimbal/pg-mem#1]
Since [you asked a question](https://github.com/vitaly-t/pg-promise/issues/743) about supporting it in [pg-promise], I want to ask a question back at you...

Would it not be more sensible to provide automation around [install-less testing](https://www.postgresonline.com/journal/archives/172-Starting-PostgreSQL-in-windows-without-install.html)?

There are ways, you know, to run PostgreSql without installing anything. It would be 100% consistent with a proper server, and not require all that complexity of emulating a PostgreSql server.

[pg-promise]:https://github.com/vitaly-t/pg-promise

**Comment by oguimbal** [comment]
Fair enough 👍 

There are other solutions, of course... but setting up one real instance of postgres per unit test seems largely overkill to me, and not practical. On the other hand, setting up one instance to run thousands of tests can be done, but it brings two problems:

- It is a bit slow to setup and prevents rapid development (I dont like to wait even a second while running a test while I am working on a feature)
- It brings a shared state amongst all your tests. Which means that the order of execution of your test matters. This has driven me mad a couple of times.

I wrote a small article about it, but [here is what I like](https://dev.to/oguimbal/how-to-really-unit-test-code-that-uses-a-db-3gmg) when I work, and this lib allows me to have this kind of experience with just an npm install, no binaries, no funkie-platform-dependent script:

![capture](https://user-images.githubusercontent.com/8973947/89100611-ae6dc100-d3f8-11ea-842d-e0c11dcfe1a8.gif)

**Comment by oguimbal** [comment]
[Added some answer in the FAQ](https://github.com/oguimbal/pg-mem/wiki/FAQ)
