### ISSUE TITLE
Aggregated queries redundant result

### ISSUE THREAD

**Issue by imatveev** [oguimbal/pg-mem#121]
Example:
```
create table example(id text, a int);
select id, sum(a) as sum from example group by id
```
Result:
```
[{
    id: null
    sum: null
 }]
```
Expected result:
`[ ]`
If I'm not missing anything, checked how real Postgres behaves.
I would be happy to assist with a fix but need some guidance on where the problem may be

**Comment by oguimbal** [comment]
Thanks !

I just happened to know exactly the fix, dont worry (cf. the commit I pushed).

Thanks for your offer, though :)

**Comment by imatveev** [comment]
Thank you!
