### ISSUE TITLE
using knex migrations and seed

### ISSUE THREAD

**Issue by capan** [oguimbal/pg-mem#145]
### Discussed in https://github.com/oguimbal/pg-mem/discussions/106

<div type='discussions-op-text'>

<sup>Originally posted by **codelover2k** May  2, 2021</sup>
hi!
I am using knex with multiple migration files.

I know that you can use knex with pg-mem, but is there a way to tell pg-meme to use knex and create the database with the multiple migration files and use knex seed functionality all in one step for each test?

A simple example would be great. Thanks!</div>

During the execution of migration files receiving error even with valid SQL queries. E.g;

```
💔 Your query failed to parse.
This is most likely due to a SQL syntax error. However, you might also have hit a bug, or an unimplemented feature of pg-mem.
If this is the case, please file an issue at https://github.com/oguimbal/pg-mem along with a query that reproduces this syntax error.

👉 Failed query:

    alter table "business" add column "iban" text, add column "deposit_period" integer;

💀 Syntax error at line 1 col 46:

  alter table "business" add column "iban" text,
                                               ^
Unexpected comma token: ",". Instead, I was expecting to see one of the following:

    - A "dot" token
    - A "lparen" token
    - A "kw_array" token
    - A "lbracket" token
    - A "kw_collate" token
    - A "kw_constraint" token
    - A "kw_unique" token
    - A "kw_null" token
    - A "kw_default" token
    - A "kw_check" token
    - A "kw_primary" token
    - A "kw_not" token
    - A "word" token
    - A "semicolon" token
```

**Comment by oguimbal** [comment]
This is on my todo list... the parser does not support parsing ALTER statements that are altering more than one columns. See [https://github.com/oguimbal/pgsql-ast-parser/issues/57](this issue)
