### ISSUE TITLE
Strict typeorm peerDependency version

### ISSUE THREAD

**Issue by tafaust** [oguimbal/pg-mem#152]
Hi, first of - great work you have been doing here! Thank you!

This issue targets the typeorm peerDependency listed here:
https://github.com/oguimbal/pg-mem/blob/master/package.json#L109

I am currently using `nestjs` with `@nestjs/typeorm` that has the typeorm peerDependency leniently listed as:
https://github.com/nestjs/typeorm/blob/master/package.json#L59

Can the strictness of the version lock for typeorm be lifted as described in https://nodejs.org/es/blog/npm/peer-dependencies/#using-peer-dependencies?
Thank you!

**Comment by oguimbal** [comment]
Hi, sorry for that very late reply, I dont know how I missed this.

See my comments on your PR :)

**Comment by tahesse** [comment]
Thanks @tankist & @oguimbal !
