### ISSUE TITLE
Fix the migrations file regexp

### ISSUE THREAD

**Issue by braccolucianoj** [oguimbal/pg-mem#159]
At first thank you for the awesome work! 

I've seend that the migrations file regular expression is not able to set as valid some names that contains strings and also split files with multiple dots
`
          files
            .map(x => x.match(/^(\d+).(.*?)\.sql$/))
`

Wouldn't it be better to check only if the file ends up with `.sql`?

**Comment by oguimbal** [comment]
Hi ! Thanks :)

That is more or less what this regex does, and more... il checks for names with digits + ending with ".sql" except that it is forgiving if the file ends up with a name like `59389385....sql`  and accepts it.

Moreover, this is not my code. I copy pasted all that from a well known migration tool (dont remember which... it was a feature request in an issue, if you want to search for it.. .and I may have documented it somewhere...).
So I would prefer to remain ISO with this tool 👉 Which means not changing anything about migration this 😅

**Comment by braccolucianoj** [comment]
Thanks for the quick response. Oh that’s good to know. Thanks
