### ISSUE TITLE
Database may not be restoring?

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#17]
Not sure if I'm missing something here but:

```
const inMemoryDb = newDb();
inMemoryDb.public.none(fs.readFileSync('src/graphql/DB/pgMem/migrations/001-initial.sql', 'utf8'));
const backup = inMemoryDb.backup();
export { inMemoryDb, backup };
```

When I run this at the top of every test, it doesn't seem like it's resetting the DB to the initial migration because in `001-initial.sql` I do not seed any "Crafters" for the Crafter table.   No crafters were created in 001-initial.sql'.  My tests create crafters.

But when I run my tests, it's not clearing crafters that were created after each test runs it seems.  If I output select * from crafters, it seems to be aggregating them.
```
beforeEach(() => {
  backup.restore();
});
```
My tests are mainly mocha.  A few are test.  Right now I'm just talking about the ones using mocha.

**Comment by dschinkel** [comment]
I think it's working nevermind.

**Comment by alexrusenhack-loft** [comment]
Hi @dschinkel , what was wrong? I am facing similar problem.

**Comment by dschinkel** [comment]
I'm not longer using pg-mem as it's not being supported.  I don't recall what the exact problem was if any.

**Comment by oguimbal** [comment]
pg-mem is being supported.

You've got some nerve saying that @dschinkel .

I've answerered [most all of your numerous pseudo-issues](https://github.com/oguimbal/pg-mem/issues?q=is%3Aissue+author%3Adschinkel), even if most of them were unrelated to pg-mem.

... Then you started sending me 5 emails per day on my personal address (still mostly unrelated to pg-mem), which were sometimes aggressive (depending on the hour they were sent).

So yes, after spending hours trying to answer you at first (and free of charge), I began to take "some time" to answer.

If you want professional support @dschinkel, I would suggest a meaningful donation. I usually charge 300$/hr, and I think I lost nearly a day answering your questions and adding the features you asked for. So do the math, and donate, before casually telling that pg-mem is not being supported.

**Comment by oguimbal** [comment]
@alexrusenhack-loft if your problem has not yet been solved, and if you have some details to reproduce the problem, please create an issue (this issue has not engough info to confirm there is an actual bug in pg-mem... that could be anything)

**Comment by dschinkel** [comment]
We have not heard a damn thing from you in almost a year.

> I have two companies to run
maybe you should not open source this

I was basically the only one really using this new repo in the beginning, when those were raised.  So I was trying to help you by giving you feedback and surfacing simple issues...most of which ended up being "pg-mem can't do that" and "can't do that" was simple things we should be able to do like CTEs, etc.

Most the simple things are still missing.  Stuff you should have been concentrating on.

Yet what have you done?  concentrated more on creating wrappers for everything for pg-mem, instead of making it usable first.  You site that you're trying to remain "agile" by supporting ORMs, but to me that seems totally not thin slicing.

You should be thin slicing the simple behaviors many have been surfaced not just by me but many others first.  Not creating wrappers for every ORM out there on your barely workable database.

You state that this is only enough functionality for tests.  Yet we still can't do simple SQL statements such as CTEs, and others.  So how in the world would we build anything on an in-memory DB that can't even function as a minimal DB yet.

Professional support? I can't even run CTEs in this thing.  And since nobody has heard from you in 8+ months, why would I support this anymore.  

You have too much going on, as evident from issues, recent, many that are coming in that are sitting there for months and months with nothing going on.

What you've done is open sourced something that you will only be using.  So don't open source it if you're not serious about it nor have the time to even reply or manage the simple things for this repo.

Kick me out, I don't fucking care man.

**Comment by dschinkel** [comment]
I'm done with this.  Especially due to your last reply.  Good luck in 2022.
