### ISSUE TITLE
Cannot use [] expression on type point

### ISSUE THREAD

**Issue by ebertmota** [oguimbal/pg-mem#173]
# Describe the bug

I have a Postgres query where I am trying to calc a distance between two address, using postgis `ST_Point` and get this error:

```md
 data: {
          error: 'function st_point(float,float) does not exist',
          hint: '🔨 Please note that pg-mem implements very few native functions.\n' +
            '\n' +
            ' 👉 You can specify the functions you would like to use via "db.public.registerFunction(...)"'
        },
```
So i try to register the `St_Point` function
```ts
  db.public.registerFunction({
    name: 'st_point',
    args: [DataType.float, DataType.float],
    returns: DataType.point,
    implementation: (x, y) => ({
      x,
      y,
    }),
  });
```
and get this error:
```
      data: {
          error: 'Cannot use [] expression on type point',
          code: undefined
        }
```

# To Reproduce

Install postgis extension
```sql
CREATE EXTENSION postgis
```
Run some query using `ST_POINT`, example:
```sql
ST_Point(-49.2786973, -25.4191268)
```

# pg-mem version
2.1.7

**Comment by oguimbal** [comment]
I think the error is somewhere else.

Doing what you describe works:

![image](https://user-images.githubusercontent.com/8973947/142699652-139a5a68-f50a-4ac2-b3ba-71b8ac9c181d.png)


Please reopen this issue with more details if needed :)
