### ISSUE TITLE
Select returns the field of text data type as a JSON object

### ISSUE THREAD

**Issue by Pulemet** [oguimbal/pg-mem#175]
# Describe the bug

There is a table:
`CREATE TABLE chat_message (chat_id uuid, user_id integer, created_at integer, message text, user_type text, type text, id SERIAL);`

Message field - is text. But the value of the message can be a JSON object. I convert json object to string to insert it into the table.
`data.message = JSON.stringify(data.message)`
`var newMessage = await db.query('INSERT INTO chat_message (..., message, ...) VALUES (..., ${data.message}, ...) RETURNING *')`

As a result, newMessage.message looks like text below:
`{"original_name":"image.png","name":"5f72f6b052076.png","type":"image/gif","size":100500,"url":"https://5f72f6b052076.png"}`

But if selecting chat_messages - message field is returned as JSON.
`var newMessage = await db.query('SELECT * FROM chat_message where id = ${id}')`

As the result, newMessage.message looks like JSON object. Example:
```
{
  original_name: 'image.png',
  name: '5f72f6b052076.png',
  type: 'image/gif',
  size: 100500,
  url: 'https://5f72f6b052076.png'
}
```
This breaks my logic, because I use `JSON.parse` method for the `message` field after selecting from the database working with real postgresql database.

# To Reproduce

```sql
CREATE TABLE chat_message (chat_id uuid, user_id integer, created_at integer, message text, user_type text, type text, id SERIAL);
INSERT INTO chat_message (chat_id, user_id, created_at, message, user_type, type) VALUES ('42a0f4ca-95d5-476b-803e-16012502802a', 1, 1637653933, '{"original_name":"image.png","name":"5f72f6b052076.png","type":"image/gif","size":100500,"url":"https://5f72f6b052076.png"}', 'user', 'file') RETURNING *
SELECT * FROM chat_message where id = 1
```

# pg-mem version 

"pg-mem": "^2.1.9"

**Comment by oguimbal** [comment]
Cant reproduce with the info you provided, sorry :/

![image](https://user-images.githubusercontent.com/8973947/143690934-a0dacfd6-cf25-4d0f-b2ed-b95a264cf506.png)

Please reopen with more actionable info, but from where I stand for, I dont see any bug.

As a side note: Unless there is a specific use case I dont see, it is not really healthy to store JSON data a text column... there is the `json` or `jsonb`  types for that
