### ISSUE TITLE
Multiple queries to same DB instance, same test?

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#18]
I'd expect that I still would find a crafter in the DB.  I confirmed that it does insert a crafter here.  But in the second graphQL call when pg-mem looks for the crafter previously insterted, it's lost, that table is empty again for some reason:

```
it('fetches a crafter by username', async () => {
  const graphQLReturnFields = 'firstName';
  const craftersStub = [{ ...crafterInputStub }];
  craftersStub[0].firstName = 'Dave';
  craftersStub[0].lastName = 'Schinkel';
  await addCraftersGraphQL(craftersStub, graphQLReturnFields); // verified it successfully adds it to the DB here

  const query = {
    query: `query {
      crafter(username: "${username}") {
        username,
      }
    }`,
  };
  const response = await sendQuery(query); // it doesn't find the added crafter above in the DB when it tries to query again because for some reason the crafter table is empty after a second call to the DB
  const { crafter } = response.body.data;

  expect(crafter.username).to.exist;
});
```

**Comment by oguimbal** [comment]
There is not enough information here to understand your problem...

My bet is that there are multiple databases, or that a transaction is created, but not committed.

Try to add something like this once your db has been setup in order to investigate:

```typescript
myDb.on('query', sql => { console.log(sql) });
```

I'm closing this, reopen if needed !

**Comment by dschinkel** [comment]
I wonder if it's because this set of tests are calling a GraphQL service and somehow my singleton which creates the DB instance is only a singleton in the code for the service but somehow it's creating a new instance in a new process or something when I run tests in code outside that service folder
