### ISSUE TITLE
toPostgres support

### ISSUE THREAD

**Issue by Smtih** [oguimbal/pg-mem#181]
node-postgres supports a function called `toPostgres` on entities that  are passed as parameters. It directs the library on how to serialize objects being passed as query parameters. Documentation of this feature can be found on this page: https://node-postgres.com/features/queries#parameterized-query

It would be great if pg-mem could support this feature as well.
If you could give some pointers as to where changes would need to be made to support such a thing, I would be happy to try and open a PR.

**Comment by oguimbal** [comment]
Should be implemented in `pg-mem@2.2.1` !

It has only been lightly tested, though... So please open an issue if you encounter a bug :)
