### ISSUE TITLE
Support the question mark jsonb operator 

### ISSUE THREAD

**Issue by MatthieuVegreville** [oguimbal/pg-mem#183]
Hello,

First, thanks again for this awesome project that have a huge potential of speeding up all our unit tests.
Currently, we are stuck because the jsonb question mark operator (which serves to check if a field of a json is present) is not supported.
Then we get this error for the queries: 
` QueryFailedError: operator does not exist: jsonb ? text`

We actually wouldn't need this operator for the tests (we just use it for db constraints on translations) but its presence in the queries make them fail.
Is there a way / a hack to prevent this? For other jsonb methods like jsonb_typeof, we use the registerFunction method but I don't see this possible here?

Thanks a lot,
Matthieu

**Comment by oguimbal** [comment]
Thanks, that's nice to hear.

To keep the library lightweight (and to spare some of my time), I have not implemented all operators.

However they are, like cusotm methods, quite easy to register and implement yourself. You can use `myDb.registerOperator()`.

For instance, see [this binary operator](https://github.com/oguimbal/pg-mem/blob/864cc4301d7edacc5a04f8a85b645400bf0c0a79/src/schema/pg-catalog/binary-operators.ts#L110-L127) as a blueprint !

If you implement it, do not hesitate to open a PR adding it in the above file if you feel like it :)

**Comment by MatthieuVegreville** [comment]
Thanks Olivier, I could make it work with the following implementation:
```
db.public.registerOperator({
      operator: '?',
      left: DataType.jsonb,
      right: DataType.text,
      returns: DataType.bool,
      implementation: (json, field) => field in json,
    });
```
I'll push PRs for these once I can make work our full set-up. Actually, as a company (Offspend/Greenly), we'd be interested in supporting this project (financially and/or dev resources) if this can solve our velocity problems in tests.

Thanks,
Matthieu

**Comment by oguimbal** [comment]
Greenly ?
Marrant. Ma soeur commence un stage chez vous en mai !

Ca sera avec plaisir, mon adresse email est sur mon profil github pour passer en privé
