### ISSUE TITLE
Support drop constraint 

### ISSUE THREAD

**Issue by MatthieuVegreville** [oguimbal/pg-mem#184]
Hello, 

I'm back with a new question :)

Is there a way to support or register a drop constraint?

Right now, this query `ALTER TABLE "alternative" DROP CONSTRAINT "UQ_05c85f2a2a06d1793b36fd69976"` gives the following error

```
 Unexpected kw_constraint token: "constraint". Instead, I was expecting to see one of the following:
    
        - A "kw_column" token
        - A "word" token
        - A "kw_primary" token
        - A "kw_unique" token
        - A "word" token

```
Is this something that could be easily added to the library if it is not implemented yet? I could do a PR.

Thanks,
Matthieu

**Comment by oguimbal** [comment]
Implemented in `pg-mem@2.2.2`
