### ISSUE TITLE
Support '0' in inserts for boolean 

### ISSUE THREAD

**Issue by MatthieuVegreville** [oguimbal/pg-mem#185]
Hello,

In PostgreSQL documentation '0' is equivalent to false for boolean types ([https://www.postgresql.org/docs/9.1/datatype-boolean.html](https://www.postgresql.org/docs/9.1/datatype-boolean.html)) and it seems that TypeORM is taking this literally because it converts the insert of an entity with a boolean to a query with '0' like this:
`INSERT INTO "purchase_category"("id", "booleanValue") VALUES ('edab89de-b3a3-4637-9095-2c16c68afb9c',  '0')`
Here, booleanValue was false in our Typescript code (i.e., we didn't set it to '0', TypeORM did)

It throws the following pg-mem error: `QueryFailedError: cannot cast type text to bool in string 0`

Do you see a simple way to support this? Otherwise, I suppose it would prevent a lot of TypeORM users from using any boolean type.

Thanks again,
Matthieu

**Comment by oguimbal** [comment]
Fixed in `pg-mem@2.2.2`  ([corresponding commit](https://github.com/oguimbal/pg-mem/commit/ba62be739babf6405df977e6c084898dc094c146) linked to the wrong issue)
