### ISSUE TITLE
concat function does not follow the PostgreSQL definition 

### ISSUE THREAD

**Issue by pomgui** [oguimbal/pg-mem#187]
# Describe the bug

The `concat` function does not follow the [PostgreSQL definition](https://www.postgresql.org/docs/9.1/functions-string.html#FUNCTIONS-STRING-OTHER).

**Definition:** Concatenate all arguments. NULL arguments are ignored.

pg-mem is not following: "NULL arguments are ignored"

# To Reproduce

Executing in a PostgreSQL instance:
```sql
psql (11.12)
pgserver=> select concat('text-', null, 123, null, '-end');
    concat    
--------------
 text-123-end
(1 row)
```

Executing in [pg-mem playground](https://oguimbal.github.io/pg-mem-playground/):
```sql
select concat('text-', null, 123, null, '-end');
--> concat: NULL
```

# Workaround

When every parameter that can be `NULL` is enclosed with a `coalesce` function, it returns the same as in PG.

```sql
select concat('text-', coalesce(null, ''), 123, coalesce(null, ''), '-end');
--> concat: text-123-end

```

# pg-mem version

pg-mem@2.3.0

**Comment by oguimbal** [comment]
Hi ! Indeed, I forgot to flag the `coalesce` function as accepting `null` arguments.

Fixed with `pg-mem@2.3.1` !

Thanks for the feedback.

**Comment by pomgui** [comment]
Thank you for such a great software!

**Comment by oguimbal** [comment]
Thanks :)
