### ISSUE TITLE
QueryFailedError: operator does not exist: character varying ~ text

### ISSUE THREAD

**Issue by emericspiroux** [oguimbal/pg-mem#188]
# Describe the bug

We need to check `insee_code` text validity with a Regex but `pg-mem` doesn't implement this syntax.

```
QueryFailedError: operator does not exist: character varying ~ text
```

# To Reproduce

```sql
CREATE TABLE "taxes_city" ("id" SERIAL NOT NULL, "insee_code" character varying(5) NOT NULL, "tax_rate" double precision NOT NULL, "start_date" date NOT NULL, "end_date" date, CONSTRAINT "taxes_city_insee_code" CHECK ("insee_code" ~ '[A-Z0-9]{5}'), CONSTRAINT "PK_af333bf8b2bfdb4a93a770fc92e" PRIMARY KEY ("id"));
```

# pg-mem version
`2.3.2`

**Comment by oguimbal** [comment]
Hi !

To keep the library lightweight (and to spare some of my time), I have not implemented all operators.

However they are, like custom functions, quite easy to register and implement yourself. You can use `myDb.public.registerOperator()`.

For instance, see [this binary operator](https://github.com/oguimbal/pg-mem/blob/864cc4301d7edacc5a04f8a85b645400bf0c0a79/src/schema/pg-catalog/binary-operators.ts#L110-L127) as a blueprint !

If you implement it, do not hesitate to open a PR adding it in the above file if you feel like it :)

nb: `registerOperator()` is quite new. Upgrade pg-mem to if you dont have it
