### ISSUE TITLE
ColumnNotFound [Error]: column "pg_type.oid" does not exist

### ISSUE THREAD

**Issue by maymayman** [oguimbal/pg-mem#194]
`import { newDb } from 'pg-mem';
import { Sequelize, DataTypes } from 'sequelize';

export async function sequelizeSample(force?: boolean) {

    // ========= CONNECT ==========

    // Create a new DB instance
    const mem = newDb();

    const sequelize = new Sequelize({
        dialect: 'postgres',
        dialectModule: mem.adapters.createPg(),
    });

    // await seq.authenticate();
    const User = sequelize.define('User', {
        // Model attributes are defined here
        firstName: {
            type: DataTypes.STRING,
            allowNull: false
        },
        lastName: {
            type: DataTypes.STRING
            // allowNull defaults to true
        }
    }, {
        // Other model options go here
    });

    await sequelize.sync({ force }).then(() => console.log('sync success')).catch((err) => console.error(err));
}

sequelizeSample();`

I try to test pg-mem but receive the message

`ColumnNotFound [Error]: column "pg_type.oid" does not exist

🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.

*️⃣ Failed SQL statement: WITH ranges AS (  SELECT pg_range.rngtypid, pg_type.typname AS rngtypname,         pg_type.typarray AS rngtyparray, pg_range.rngsubtype    FROM pg_range LEFT OUTER JOIN pg_type ON pg_type.oid = pg_range.rngtypid)SELECT pg_type.typname, pg_type.typtype, pg_type.oid, pg_type.typarray,       ranges.rngtypname, ranges.rngtypid, ranges.rngtyparray  FROM pg_type LEFT OUTER JOIN ranges ON pg_type.oid = ranges.rngsubtype WHERE (pg_type.typtype IN('b', 'e'));;`

am i missing anything?
i am using 
"node": "14.16.0",
"pg-mem": "^2.3.3",
 "sequelize": "^6.17.0"

**Comment by oguimbal** [comment]
Hi,

That's weir... I dont have this issue with sequelize@6.17.0

...Can you give me the exact version that is installed ?  as seen when running:
```bash
cat node_modules/sequelize/package.json | grep version
```

**Comment by jnrbarros** [comment]
I got the same error with `sequelize@6.19.0`

**Comment by JoniBR** [comment]
same error for me with  6.19.0
