### ISSUE TITLE
Reuse static backup across multiple tests

### ISSUE THREAD

**Issue by Smtih** [oguimbal/pg-mem#199]
The backup feature of pg-mem is super useful.

It seems to me a useful use case for it is to set up tables and add a bunch of static data before the test suite starts.
At the moment I do this per test, but I feel that it should be faster to do this once and clone this state to each test.
Is such a thing possible with the current functions and I just can't work it out?

**Comment by oguimbal** [comment]
Hi !

Yes, [restore points](https://github.com/oguimbal/pg-mem#rollback-to-a-previous-state) are doing exactly that :)

**Comment by Smtih** [comment]
Sorry @oguimbal I didn't explain myself well enough. The Restore points are useful in the context of a single test, but I want to be able to use seperate db instances per test that restore to an initial state from a common backup.

```ts
// Global Test Setup

const db = newDb();
// Do migrations
// Seed Test data
__global__.dbBackup = db.backup()
```
Then later in each test

```ts
// Before each test is executed

const db = newDb();
db.restoreFrom(__global__.dbBackup);
```
