### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by MirrorBytes** [oguimbal/pg-mem#2]
Might want to throw into documentation that you need to import using ```import { newDb } from 'pg-mem/src';``` if you want types to work properly.

**Comment by oguimbal** [comment]
Hi !

That was definitely not intended.
Thanks for the report. This should be fixed in 1.2.0 I just published, tell me if its not !

(nb: "src" directory does not exists anymore in 1.2.0)

**Comment by MirrorBytes** [comment]
All good now! Thank you
