### ISSUE TITLE
Issue with registerFunction

### ISSUE THREAD

**Issue by MirrorBytes** [oguimbal/pg-mem#20]
So I've been adding more tests to a project of mine, and I'm getting this error:

```error
Unique constraint violated while adding a record to index PK_cace4a159ff9f2512dd42373760
```

This error is thrown when I try to create a second entry (with a uuid) in my test environment.

Here's the `registerFunction` call I use to implement uuid generation:

```typescript
    mem.registerExtension('uuid-ossp', (schema) => {
      schema.registerFunction({
        name: 'uuid_generate_v4',
        returns: DataType.uuid,
        implementation: v4,
      });
    });
```

It appears to me that the uuid is generated on table creation (and used for every item inserted), not on insertion, which can become problematic when more complex relations are tested.

**Comment by oguimbal** [comment]
Could you try defining this function as a non pure function ?


```typescript
schema.registerFunction({
        name: 'uuid_generate_v4',
        returns: DataType.uuid,
        implementation: v4,
        impure: true,
      });
```

For performance reasons, pg-mem optimizes away all expressions involving pure functions (to avoid running calling `lower` thousands of times when running something like `select * from t where m = lower('whatever')`)

Thus, all functions implying a side-effect or returning variant data must be marked as such to prevent those optimizations.

**Comment by MirrorBytes** [comment]
That worked! Thank you!!
