### ISSUE TITLE
Support for row_to_json

### ISSUE THREAD

**Issue by testica** [oguimbal/pg-mem#209]
Postgres has a function called `row_to_json` that receives a record and transforms it to json type.

How can I implement this function with `registerFunction` ?
```
registerFunction({
            name: 'row_to_json',
            args: DataType.record,
            returns: DataType.json,
            implementation: x => ???, // No idea about the 'x' structure
        })
```
Also, pg-mem throws with `type "record" does not exist`

**Comment by oguimbal** [comment]
Since `pg-mem@2.4.1`, you can declare functions that accept a record (that said, `args` is supposed to be an array...)

So you'd like something like that, in your case:

```typescript
db.public.registerFunction({
            name: 'row_to_json',
            args: [DataType.record],
            returns: DataType.json,
            implementation: x => JSON.parse(JSON.stringify(x)),
        });
```
