### ISSUE TITLE
pg_mem is executing some script which modifies pg_hba.conf file

### ISSUE THREAD

**Issue by Ashutoshwill** [oguimbal/pg-mem#211]
# Describe the bug
pg_mem is executing some script which modifies pg_hba.conf files. I am trying to set trust as connection method but when ever pg_mem starts executing it reset it to md5. Also it makes all user NONSUPERUSER except one. Please help me understand why this is happening and how we can resolve it.
(Describe your issue here).

```
(pg-mem tries to throw nice error messages when possible... so paste it here if you have one !)
```

# To Reproduce

```sql

"If possible, paste here (including create table statements) a query that fails on https://oguimbal.github.io/pg-mem-playground/, but suceeds when ran on an actual PG database"

```

# pg-mem version

(paste your pg-mem version here)

(nb: the version in your package.json version is often not precise enough... please run "cat ./node_modules/pg-mem/package.json | grep version" to tell which minor version is actually installed)

**Comment by oguimbal** [comment]
Hi, I think you're mistaken... there is no code in pg-mem which modifies any file. There is only ONE place where filesystem is accessed: it is when you call the .migrate() function, but even then, only a readFile is performed.

... this must come from something else which is not pg-mem related 🤷‍♂️
