### ISSUE TITLE
ORDER BY does not work with field alias

### ISSUE THREAD

**Issue by pomgui** [oguimbal/pg-mem#216]
# Describe the bug

A query with an ORDER BY clause using a field alias instead of its name or its ordinal position fails.

# To Reproduce

```sql
CREATE TABLE test(field int);
CREATE TABLE

INSERT INTO test values (1),(2),(3);
INSERT 0 3

-- This works in pg & pg-mem
SELECT field FROM test ORDER BY field;
 field 
-------
     1
     2
     3
(3 rows)


-- This also woks in pg & pg-mem
SELECT field FROM test ORDER BY 1;
 field 
-------
     1
     2
     3
(3 rows)

-- But this does not work in pg-mem
SELECT field AS alias FROM test ORDER BY alias;
 alias 
-------
     1
     2
     3
(3 rows)



```

# pg-mem version

```
node -p "require('./node_modules/pg-mem/package.json').version"
2.3.5
```

**Comment by oguimbal** [comment]
Fixed in `pg-mem@2.4.0`

Thanks for the report

**Comment by pomgui** [comment]
One thing I completely forgot to mention until reading your answer right now: GROUP BY has exactly the same behavior than ORDER BY.

Sorry for that. If you want, I can open a new issue for it.

BTW: Both behaviors (order and group with aliases) are shared in various RDBMS I worked with: Firebird, Oracle, MySQL, SQLServer, and PostgreSQL.

**Comment by oguimbal** [comment]
Hi, I also fixed the same issue for group-bys [in this commit](https://github.com/oguimbal/pg-mem/commit/accb3cdadaa401270f56265055f2adb8ece46eb3#diff-1b2ef1627e3d09d12cb1a898e7b4718088a12dcb79daecbb7dbc47a055672a37R134) could you confirm that it doesnt work with the latest pg-mem version ?

Can you provide an example ?

**Comment by pomgui** [comment]
Sorry for the delay. I've tested it and GROUP BY with alias works in 2.4.0. However it does not work with ordinal position. I've created a new issue #247
