### ISSUE TITLE
SELECT accepts bogus column if ORDER BY present

### ISSUE THREAD

**Issue by gthb** [oguimbal/pg-mem#228]
# Describe the bug

A query like `SELECT bogus FROM test` where `test` does not have a column named `bogus` throws an error, as it should.

But if you add `ORDER BY somecol` (where `test` _does_ have the column `somecol`), it doesn't throw an error, but instead returns a result set with a column named `bogus` whose values are whole row objects.

# To Reproduce

```sql
create table test(id text, name text, value text);
insert into test values ('0123', 'Gulli', 'Floob');
insert into test values ('0123', 'Briem', 'Blaab');
select bogus from test;
select bogus from test ORDER BY value;
```

The first `select` statement fails with the error `column "bogus" does not exist`, as it should.

Remvoe that, and the second `select` statement incorrectly returns:
```
bogus
--
{     "id": "0123",     "name": "Briem",     "value": "Blaab" }
{     "id": "0123",     "name": "Gulli",     "value": "Floob" }
```

# pg-mem version

2.4.3

**Comment by oguimbal** [comment]
Hi ! Fix released in `pg-mem@2.6.0`  :)
