### ISSUE TITLE
Run a query expressed as an AST, not SQL text

### ISSUE THREAD

**Issue by gthb** [oguimbal/pg-mem#235]
In my use case I want to transform a query with `astMapper` before executing it. So I'm doing something like this:
```js
const queryAST = parse(sqlText)[0];
const transformedQueryAST = astMapper(...).statement(queryAST);
const transformedSqlText = toSql.statement(transformedQueryAST);
const result = db.public.query(transformedSqlText);
```

... and of course that `.query` call then parses the SQL I hand it ... back to the AST which I already had in `transformedQueryAST`. I'd like to just pass it the AST directly and skip the serialize-and-parse-again work.

Would it be reasonable to let `ISchema.queries` accept `string | Statement[]` so the parsing is only done when the input is a string?

The `this.db.raiseGlobal` event payloads could be the `Statement[]` when that's the input (they're typed as `...args: any[]` and AFAICT not really specified to be SQL text, so this seems OK).

Could do this for the other methods of `ISchema` too, but that would mean deciding what to do for interceptors etc., so maybe simplest to support it only in `queries`.

**Comment by oguimbal** [comment]
Hi ! Feature released in `pg-mem@2.6.0`  :)
