### ISSUE TITLE
Errors importing production schema

### ISSUE THREAD

**Issue by AustinGil** [oguimbal/pg-mem#33]
Trying to follow the instructions in the wiki for importing production schema (https://github.com/oguimbal/pg-mem/wiki/FAQ#-how-to-import-my-production-schema-in-pg-mem-). I've run into some errors that I believe may not be specific to my DB.

I've run the SQL dump as shown in the example, and tried the same sample script:

```js
const fs = require('fs');
const { newDb } = require('pg-mem');

const db = newDb();

db.public.none(fs.readFileSync('dump.sql', 'utf8'));

const backup = db.backup();
```

However, I got the `Unexpected word token: "public"` error for lines that look like these:

```sql
CREATE FUNCTION public.some_name ...

CREATE AGGREGATE public.some_name ...

CREATE VIEW public.some_name AS ...

CREATE OR REPLACE VIEW public.some_name AS ...
```

And `Unexpected word token: "some_name"` for lines that look like this:

```sql
CREATE TRIGGER some_name AFTER UPDATE ON ...
```

I'm not sure if this is an issue with this library or something on my end.

**Comment by oguimbal** [comment]
Hi ! 

Which version of pg-mem are you using ? (exceptions should be nicer)

That said, functions, aggregates, triggers and views are not yet supported.

Views should be supported soon, though.

**Comment by AustinGil** [comment]
Im on version 1.6. In fact, the errors are much nicer. I didnt include the whole error for brevity. I figured just the specific error would be useful.

So it makes sense that it's not yet working for me.

On a side note, I did get it working on a very basic project. It's great!

**Comment by oguimbal** [comment]
Pleased to know that it's useful to someone :)

I'm closing this in favor of https://github.com/oguimbal/pg-mem/issues/42, https://github.com/oguimbal/pg-mem/issues/43 and https://github.com/oguimbal/pg-mem/issues/34 since they track the different issues you have separately.

Views are coming very soon.

**Comment by AustinGil** [comment]
Sounds good.
