### ISSUE TITLE
Views support

### ISSUE THREAD

**Issue by guscl** [oguimbal/pg-mem#34]
I encountered the following problem:

    💀 Syntax error at line 14 col 13:

      CREATE VIEW fleets_for_cc_users
                  ^
    Unexpected word token: "fleets_for_cc_users". I did not expect any more input. Here is the state of my parse table:
    
 Does it support the creation of views?

**Comment by oguimbal** [comment]
Hi ! Nope, views are not yet supported.

Soon :)

**Comment by oguimbal** [comment]
Reopening this for tracking !

**Comment by oguimbal** [comment]
Hi ! 
Simple views are implemented in `pg-mem@1.8.6` ... to be noted:
- The implementation is a bit fragile, meaning that an `ALTER` request on the underlying table might silently screw up the view (there is no check preventing to drop a column used in a view, for instance)
- Materialized views are (temporarily) implemented as simple views. Meaning that you dont get the performance benefit from a materialized view, and you cant (yet) create indices on them.
- Temp views are not supported.
- Recursive views are not supported.
