### ISSUE TITLE
"insert into select" support   (todo: array-mode iteration error)

### ISSUE THREAD

**Issue by hallvors** [oguimbal/pg-mem#35]
This is code express-session appears to use. Support for this would certainly be nice :+1: although it seems a bit complicated. I'm not sure what the point of an inner SELECT query is here since it is not actually looking up values from elsewhere but just providing them directly, but somebody better versed in SQL might know why this is clever.

 Error: todo: array-mode iteration
     
    *️⃣ Failed SQL statement: INSERT INTO "express_server_sessions" (sess, expire, sid) SELECT '{"cookie":{"originalMaxAge":1296000000,"expires":"2021-01-29T15:49:27.925Z","secure":true,"httpOnly":true,"path":"/"},"passport":{"user":653646}}', to_timestamp(1611935368), 'jCUSxo0EnzcIeCQYUgt6g3FQCoIO6Q3S' ON CONFLICT (sid) DO UPDATE SET sess='{"cookie":{"originalMaxAge":1296000000,"expires":"2021-01-29T15:49:27.925Z","secure":true,"httpOnly":true,"path":"/"},"passport":{"user":653646}}', expire=to_timestamp(1611935368) RETURNING sid;

PS: to run this code in the first place I had to work around the lack of to_timestamp:
```
const pgMem = require('pg-mem');
const mockDb = pgMem.newDb();


mockDb.public.registerFunction({
  name: 'to_timestamp',
  args: [pgMem.DataType.integer],
  returns: pgMem.DataType.timestampz,
  implementation: input => {
    return new Date(input * 1000).toISOString();
  },
});

```

**Comment by oguimbal** [comment]
Yup...  `insert into select`  is not implemented (thanks, procrastination)... I'll do that soon.

Thanks for the report

**Comment by dschinkel** [comment]
This is basically the last thing I need pg-mem to do for me that will allow me to continue to use pg-mem for the majority of my use cases.  Hope to see this working soon, I know you're busy but it's critical that I be able to do inserts dynamically like this in my workflow in a real app.

**Comment by dschinkel** [comment]
I need to be able to use multiple sub selects not just one because for some inserts I need to be able to pull data from different tables for the insert, so please take that into consideration when you resolve this.

e.g.
```sql
INSERT into foo_bar (foo_id, bar_id) VALUES 
((select id from foo where name = 'dave'), (select id from bar where type = 'name'));  
```

**Comment by dschinkel** [comment]
I am busy looking for jobs, any update on getting to this?

**Comment by oguimbal** [comment]
I couldnt find any time to work on that this week, but it's almost done.
I'll keep you posted, hopefully next week.

**Comment by oguimbal** [comment]
Hi !

This should be fixed in `pg-mem@1.7.3`

**Comment by dschinkel** [comment]
@oguimbal I was looking at your tests for this.  Did I miss something or did you not implement the ability to run multiple selects for the insert?

**Comment by oguimbal** [comment]
@dschinkel  No, that is not yet fixed 🤔 but this is not related to this issue, since this is not an insert-into-select... 

Actually, would also have this error like that: `select * from test where id=(select  id from test limit 1)`

I created #58 for tracking
