### ISSUE TITLE
Support for aggregate function max

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#36]
Would like to be able to run something like this:

`select setval('skills_skill_id_seq',select max(id) from skills);`

Error: `NotSupported [Error]: 🔨 Not supported 🔨 : aggregation function max`

**Comment by oguimbal** [comment]
Hi !

Yup... not implemented. Adding that to my todolist.

Adding new aggregation functions should be quite easy, though. For instance, [this is how count(column) is implemented](https://github.com/oguimbal/pg-mem/blob/4b8a36d53e481916ba4291e045ac6edae8682b31/src/transforms/aggregation.ts#L382-L403).


PR are welcome :)

**Comment by dschinkel** [comment]
I would contribute if I have time, but I work on my own site [WeDoTDD.com](WeDoTDD.com) that takes all of my time outside work.

**Comment by oguimbal** [comment]
Hi !

This should be fixed in `pg-mem@1.6.3` 😊

**Comment by dschinkel** [comment]
Really appreciate this!  I'll be trying it out soon!
