### ISSUE TITLE
Missing support for EXTRACT datetime

### ISSUE THREAD

**Issue by cyrille-arundo** [oguimbal/pg-mem#40]
Specification: https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT

💔 Your query failed to parse.
This is most likely due to a SQL syntax error. However, you might also have hit a bug, or an unimplemented feature of pg-mem.
If this is the case, please file an issue at https://github.com/oguimbal/pg-mem along with a query that reproduces this syntax error.

👉 Failed query:

    SELECT EXTRACT(EPOCH FROM TIMESTAMP  '2001-02-16 20:38:40.12-08');
;

💀 Syntax error at line 1 col 22:

  SELECT EXTRACT(EPOCH FROM
                       ^
Unexpected kw_from token: "from". Instead, I was expecting to see one of the following:

    - A "dot" token
    - A "dot" token
    - A "lparen" token
    - A "op_cast" token
    - A "lbracket" token
    - A "op_member" token
    - A "op_membertext" token
    - A "op_exp" token
    - A "star" token
    - A "op_div" token
    - A "op_mod" token
    - A "op_plus" token
    - A "op_minus" token
    - A "op_additive" token
    - A "kw_not" token
    - A "kw_in" token
    - A "kw_not" token
    - A "op_like" token
    - A "op_ilike" token
    - A "op_not_like" token
    - A "op_not_ilike" token
    - A "kw_like" token
    - A "kw_ilike" token
    - A "kw_not" token
    - A "kw_is" token
    - A "op_compare" token
    - A "kw_notnull" token
    - A "kw_is" token
    - A "kw_isnull" token
    - A "kw_is" token
    - A "word" token
    - A "op_eq" token
    - A "op_neq" token
    - A "kw_and" token
    - A "kw_or" token
    - A "comma" token
    - A "rparen" token
    - 

See relevant issue at https://github.com/oguimbal/pgsql-ast-parser/issues/5

**Comment by oguimbal** [comment]
Hi !

Should be fixed in `pg-mem@1.6.2` 😊

Thanks for the report

**Comment by cyrille-arundo** [comment]
Thank you @oguimbal for the fix.
