### ISSUE TITLE
🚩 "CREATE FUNCTION" statement |  PL/pgSQL support (big feature)

### ISSUE THREAD

**Issue by oguimbal** [oguimbal/pg-mem#42]
This is a tracking issue. Dont hesitate to +1 if you'd like this to be implemented.

That said, it's likely not to be implemented soon, since it is a lot of work.

It would mean:
- Implement PL/pgSQL syntax [in pgsql-ast-parser](https://github.com/oguimbal/pgsql-ast-parser)
- Implement the execution engine (probably via some codgen ?)
- Implement custom languages. See [this discussion](https://github.com/oguimbal/pg-mem/discussions/41)

Contributions are welcome, but that's a tough nut to crack.

**Comment by RodolfoSilva** [comment]
> Supporting the "create function" statement, without actually parsing/compiling the function body (which would force you to declare mocks for your created pg functions directly in JS).

Hey @oguimbal what's the path that you suggest to implement this? I think this is most easy way to do this right now. Allowing the stub implementation of PSQL functions like extensions.

**Comment by oguimbal** [comment]
The path... you mean how it must be implemented ?

I've been wanting to add that in contributing.md for a while, so i'll do that now.

Like any feature of pg-mem, it breaks down into:

## A) Implement its parser

NB: For this use case (create function stubs), this will not exactly look like below, because `create function` body must be "ignored" ... thus, I think that [the lexer](https://github.com/oguimbal/pgsql-ast-parser/blob/master/src/lexer.ts) must be modified. Which is a bit tricky. But otherwise, it goes like that:

1) Look very hard at [the statement syntax](https://www.postgresql.org/docs/current/sql-createfunction.html)
2) Add the target statement type in [pgsql-ast-parser AST](https://github.com/oguimbal/pgsql-ast-parser/blob/7358e4a1fe0b3fe79ae047a936673745cc17b5f5/src/syntax/ast.ts#L6) based on what I understood.
3) Implement unit tests I want to pass (ex with [create sequence UTs](https://github.com/oguimbal/pgsql-ast-parser/blob/master/src/syntax/sequence.spec.ts))
4) Implement its syntax in a new nearley file (example with the [create sequence](https://github.com/oguimbal/pgsql-ast-parser/blob/master/src/syntax/sequence.ne) statement) and reference it in [main.ne](https://github.com/oguimbal/pgsql-ast-parser/blob/7358e4a1fe0b3fe79ae047a936673745cc17b5f5/src/syntax/main.ne#L56)
5) Work on it until unit tests are all failing, but with an error which is not a parsing error
6) Add an entry for the new statement in `IAstPartialMapper` here  and add its default visitor implem like [here](https://github.com/oguimbal/pgsql-ast-parser/blob/7358e4a1fe0b3fe79ae047a936673745cc17b5f5/src/ast-mapper.ts#L308-L313) and [here](https://github.com/oguimbal/pgsql-ast-parser/blob/7358e4a1fe0b3fe79ae047a936673745cc17b5f5/src/ast-mapper.ts#L223-L224) until compiler stops screaming
7) Add the "toSql" implementation of the new statement like [here](https://github.com/oguimbal/pgsql-ast-parser/blob/7358e4a1fe0b3fe79ae047a936673745cc17b5f5/src/to-sql.ts#L432-L443) (until compiler stops)
8) Check that ALL unit tests are green (not only the new ones)
9) Release pgsql-ast-parser


## B) Executor

1) install pgsql-ast-parser@latest
2) Write unit tests (create sequence UTs are [here](https://github.com/oguimbal/pg-mem/blob/master/src/tests/sequence.spec.ts), for instance)
3) Implement statement... that's the less codified thing, but it starts by adding a new case [in this switch](https://github.com/oguimbal/pg-mem/blob/4b8a36d53e481916ba4291e045ac6edae8682b31/src/schema.ts#L124-L219) for new statements (which should fail to compile with the newly installed pgsql-ast-parser), or fix compilation errors & unit tests for other amendments to the parser.
4) Check that ALL  unit tests are OK
5) Release 🎉

**Comment by oguimbal** [comment]
CREATE FUNCTION statements are now partially supported in `pg-mem@1.7.1`, via the [registration of custom languages](https://github.com/oguimbal/pg-mem/wiki/Custom-language-declaration-(functions,-do-statements,-plpgsql,-plv8,-...).

This allows to provide either a custom compiler (for custom scripts such as javascript via `eval()`), or a mock implementation for each function creation.

(I dont think actual plpgsql support is coming anytime soon)
