### ISSUE TITLE
newDb.adapters is undefined

### ISSUE THREAD

**Issue by adam-ashored** [oguimbal/pg-mem#48]
I feel like I must be doing something silly. 

Installed is version 1.6

I am doing this

```
import {newDb} from 'pg-mem';
const {Client} = newDb.adapters.createPg();
```

And I get this error:

```
TypeError: Cannot read property 'createPg' of undefined
```

Are [the adapter docs](https://github.com/oguimbal/pg-mem/wiki/Libraries-adapters) up to date?

**Comment by oguimbal** [comment]
My fault. Its `newDb().adapters`, not just `newDb.adapters`. I have fixed the documentation, thanks

ps: you should use Typescript 😜

**Comment by adam-ashored** [comment]
@oguimbal 

1. Thank you very much for this amazing library!
2. I am using Typescript.

**Comment by oguimbal** [comment]
You're very welcome :)
