### ISSUE TITLE
pg-promise and exporting Schemas Automatically

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#5]
**Context:**
- I am not using nor do I want to use an ORM
- I need an in-memory DB that pulls schemas exported somehow from my real DB and creates the tables

**Is there a way for me to:**
**1)** Export my schemas from my postgres DB in a format your library will take and run with that creates the tables automatically for me?

I looked at  your examples but none of them talks about some way to do what I'm saying without using an ORM.

Like does yours do something like sqlite has:

https://sqlite.org/schematab.html

**Comment by oguimbal** [comment]
Hi ! 

What would be the advantages of it compared to a create table statements script ?

**Comment by dschinkel** [comment]
I don't want to do those statements manually.  The point of having an in-memory DB is to pull the schemas for your tests and automate all that

**Comment by oguimbal** [comment]
Sure, I definitely know what you mean 👍 

I'll add some documentation to show how generate a schema export that's compatible with pg-mem (using pg_dump), and support for everything that pg_dump generates.

Thanks for the feedback.

I'll close #6, since both issues are (kind of) the same in regard of what I should do

**Comment by dschinkel** [comment]
really appreciate it!  thank you!

**Comment by oguimbal** [comment]
Hi !

If you update to `pg-mem@1.4.0`   [this should do the trick](https://github.com/oguimbal/pg-mem/wiki/FAQ#how-to-import-my-production-schema-in-pg-mem-)

I've tested it on a rather large database, it works.

Dont hesitate to tell me if it worked for you, or reopen this issue (or create another ad-horc) if doesnt.

**Comment by dschinkel** [comment]
Thanks very much for How to import my production schema in pg-mem. It's awesome documentation you added and helps.

The only thing that's missing though which I really need to be added to this in order for me to be able to use your lib is migration support / API. I can't really use this to the fullest if I can't run migrations on .sql files much like you can with node-sqlite.

I think right now you're showing mostly examples or expect people to inline sql strings in their code but that's not ideal because that's not deployable. If you are able to do this, then it would be huge and I could truly use your lib here!

**Comment by oguimbal** [comment]
Hi !

It seems that database migration is more or less just reading `.sql` files in an alphabetical order, and executing them.

`pg-mem` aims to target evry evironment (node, deno, browser). Thus, I'm not fond of the idea of embeding code that reads files in it.

That said, the logic behind sql migration [is pretty simple](https://github.com/kriasoft/node-sqlite/blob/6c0dc7f40f4342680df8cc381d4040bfd64410d4/src/utils/migrate.ts), it could easily be adapted to work with pg-mem !

I'll look into pasting a code snippet to do that when I have time.  Please let me know if you do it in the meantime !

**Comment by dschinkel** [comment]
Yea but I don't have time to write that.  The point behind SQL files and not inline SQL is for deployments.  I want to be able to push those migrations to production which is a huge deal with Continuous Deployment.  Merely having tests is only one part.  If you can't push those migrations easily (which .sql files let you do) it's kinda pointless.

**Comment by oguimbal** [comment]
Okay, [I've added it](https://github.com/oguimbal/pg-mem/commit/ec03bc0bc0f8ccd0dc28573a4414f49752953196), it works, except when using delete on cascade (which is still under development). It will be embbeded in the next pg-mem release

**Comment by dschinkel** [comment]
awesome, I'll give this a try today!!  Thanks!

**Comment by dschinkel** [comment]
also nice!  https://github.com/oguimbal/vscode-mocha-test-adapter

I use JetBrains but sure is nice to see someone is tackling the lack of a test runner in VSCode

**Comment by oguimbal** [comment]
nb: You wont be able to try it today - it's not released yet !

Thanks 👍 It's actually a fork of an existing test adapter, adding supports for HMR for a better testing experience. [I wrote a small article about it here](https://dev.to/oguimbal/zero-delay-development-unit-testing-iterations-1jk7)

**Comment by oguimbal** [comment]
@dschinkel  I had some time during lunch... `pg-mem@1.4.2` is out.

**Comment by dschinkel** [comment]
thanks a lot for doing this!  I'll be trying this out tonight and will report back how it goes!
