### ISSUE TITLE
Parsing problem with array values

### ISSUE THREAD

**Issue by adjoinant** [oguimbal/pg-mem#50]
Hi there,

Thank you for creating this package. It is great, and I'd love to use it in my tests. I have encountered the following issue with array values:

https://github.com/oguimbal/pg-mem/blob/master/src/tests/pg.spec.ts#L43 demonstrates running the following query:
`const got = await client.query('select * from data where id = $1', ['str']);`

However if I change that query to the following, then I get a syntax error and the test fails:
`const got = await client.query('select * from data where id = ANY($1)', [['str']]);`

I believe the issue relates to how javascript arrays are being treated in https://github.com/oguimbal/pg-mem/blob/master/src/adapters.ts#L11 and https://github.com/oguimbal/pg-mem/blob/master/src/pg-escape.ts#L3.

If you compare with how javascript array values are handled in node-postgres, you can see a difference:
https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/utils.js#L40
https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/utils.js#L16

How could I best help contribute to addressing this issue?

**Comment by oguimbal** [comment]
Hi !

That was effectively a bug :)

This should be fixed with `pg-mem@1.6.1` 

Thanks for the report 😊
