### ISSUE TITLE
WHERE on a serial primary key only accepts an integer

### ISSUE THREAD

**Issue by BrandonMoss** [oguimbal/pg-mem#69]
Essentially in pg it appears that the two following queries where id is a serial primary key are equivalent and return the same results:
`SELECT * FROM "photo" WHERE "id"=1;`
`SELECT * FROM "photo" WHERE "id"='1';`

pgsql-ast-parser only handles the first case. Is it possible to handle the second case?

One other strange thing is that pgsql-ast-parser does handle both cases for foreign keys. Both of these are valid and accepted queries. I believe this is correct behavior, and primary key queries should function the same.
`SELECT * FROM "photo" WHERE "userId"='2';`
`SELECT * FROM "photo" WHERE "userId"=2;`

This can be reproduced in https://oguimbal.github.io/pg-mem-playground/

**Comment by BrandonMoss** [comment]
Ah, well that would explain why I could not find the place to fix it in pgsql-ast-parser! I originally tried to see if I could make a PR with the fix, but I guess I was looking in the wrong place. Thanks for the help and the useful packages!

**Comment by oguimbal** [comment]
Fixed in `pg-mem@1.8.1`
