### ISSUE TITLE
Query failed when creating enum type

### ISSUE THREAD

**Issue by xpportal-bmo** [oguimbal/pg-mem#7]
Hello again;

First, thank you for your work on the `regclass` type. I've appreciated seeing how responsive you are with this project.

Second, I've come across an issue with `CREATE TYPE "baz" AS ENUM('foo', 'bar');`

If it helps, I've got a small repo created that replicates this issue: https://github.com/xpportal-bmo/nestjs-pg-mem-test

I'm using NestJS + typeorm + pg

- `pg-mem` implementation is here: https://github.com/xpportal-bmo/nestjs-pg-mem-test/blob/main/test/test.db.ts
- Unit test is here: https://github.com/xpportal-bmo/nestjs-pg-mem-test/blob/main/test/entity.spec.ts

Here is the full output:

```
    QueryFailedError: 💔 Your query failed to parse.
    This is most likely due to a SQL syntax error. However, you might also have hit a bug, or an unimplemented feature of pg-mem.
    If this is the case, please file an issue at https://github.com/oguimbal/pg-mem along with a query that reproduces this syntax error.

    👉 Failed query:

        CREATE TYPE "User_role_enum" AS ENUM('user', 'admin');

    💀 Syntax error at line 1 col 13:

      CREATE TYPE "User_role_enum"
                  ^
    Unexpected word token: "\"User_role_enum\"". I did not expect any more input. Here is the state of my parse table:

        kw_index → %word ● 
        kw_sequence → %word ● 
        kw_temporary → %word ● 
        kw_temp → %word ● 
        kw_extension → %word ●

      at new QueryFailedError (src/error/QueryFailedError.ts:9:9)
      at src/driver/postgres/PostgresQueryRunner.ts:220:30
      at Timeout._onTimeout (node_modules/pg-mem/src/adapters.ts:92:42)
```

**Comment by oguimbal** [comment]
Argh ! Custom types. I was secretly hoping that nobody uses them  😏 

I'll look into it.

**Comment by oguimbal** [comment]
Should be  OK with `pg-mem@1.5.0` 

![image](https://user-images.githubusercontent.com/8973947/101987078-2b0b8880-3c92-11eb-9c23-d85d690f9500.png)

**Comment by xpportal-bmo** [comment]
```
$npm run test

> nestjs-pg-mem-test@0.0.1 test nestjs-pg-mem-test
> jest

 PASS  test/entity.spec.ts
  EntityTest
    ✓ should create entity repos (2 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.323 s, estimated 17 s
Ran all test suites.
```

Worked like a charm, thank you very much!
