### ISSUE TITLE
TimestampType.doEquals is wrongly implemented

### ISSUE THREAD

**Issue by cyrille-arundo** [oguimbal/pg-mem#71]
https://github.com/oguimbal/pg-mem/blob/61cd9a04df5fc51194b48274ef7c722c54b74022/src/datatypes/t-timestamp.ts#L80

The diff can be negative. Correct implementation:

```
return Math.abs(moment(a).diff(moment(b))) < 0.1; 
```

**Comment by oguimbal** [comment]
Ouch, you're right 😱

**Comment by cyrille-arundo** [comment]
PR in progress ;)

**Comment by oguimbal** [comment]
Fixed with `pg-mem@1.7.8`  thanks to @cyrille-arundo
