### ISSUE TITLE
Possible support for mikro-orm

### ISSUE THREAD

**Issue by MirrorBytes** [oguimbal/pg-mem#95]
Is there a chance to bring in support for mikro-orm?

**Comment by oguimbal** [comment]
Hi ! 

Supported by `pg-mem@1.9.0`. See [here](https://github.com/oguimbal/pg-mem/wiki/Libraries-adapters#-mikro-orm)  to get started.

Disclaimer: I have not extensively tested it... So I'm interested to know if it works well 😁

**Comment by MirrorBytes** [comment]
Awesome, thank you! I will let you know how it goes
